### ISSUE TITLE
Made something similar

### ISSUE THREAD

**Issue by cblegare** [allonhadaya/dmenu-python#2]
Hi @allonhadaya !

I needed a dmenu wrapper with some additional features. These features would have required a massive pull request to your depot, so I pushed a [very similar project](https://github.com/cblegare/xdmenu) to github.  I also wanted to test a cookiecutter template I made (which was useful since I've found many issues in it).  That also explains the very over-engineered documentation, setup script and test folder structure.

Now that it's done, I guess we don't need both at the same and I was wondering if you could be interested in a pull request.  The two projects have different licenses, but I can change mine in order to be compatible for merging.  

The additional feature is simply to be able to add command line options to dmenu when using a patched version.  It also provides some test coverage.

What do you think?

**Comment by allonhadaya** [comment]
Hey @cblegare,

I'm glad you found this code to be a helpful starting point for what you wanted to build. It's really cool!

It took me a little while to get around to reading your code and getting a sense of what it does. I appreciate it, and I think it deserves to be its own project rather than making this simple library try to do more than it is designed to.

If you have a different sense of why they should be combined, feel free to tell me!

Thanks for your interest :)
